spring:
  datasource:
    url: jdbc:mysql://39.96.68.53:3306/parking?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5 #最小连接数
      max-active: 20 #最大连接数
      max-wait: 600000 #最大等待时间
      time-between-eviction-runs-millis: 60000 #空闲连接的检查时间间隔
      min-evictable-idle-time-millis: 300000 #
      validation-query: SELECT1FROMDUAL #解决mysql8小时的问题
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat:
          log-slow-sql: true
  servlet:
    multipart:
      max-file-size: 200MB #设置单个上传文件大小
      max-request-size: 200MB #设置一次请求上传文件的总容量
  redis:
    port: 6379
    database: 0
    host: 39.96.68.53
    password: CGredis
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 1
        min-idle: 0
    timeout: 1000
  liquibase:
    contexts: dev
    change-log: 'classpath:liquibase/master.xml'


mybatis:
  type-aliases-package: com.cs.parking.pojo
  mapper-locations: classpath:mappers/*.xml


logging:
  level:
    pre.cg.mapper: debug #指定类的日志级别
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n" #控制台输出日志格式
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n "#文件输出日志格式
  file:
    path: logs/


parking:
  uri: 39.96.68.53
  nginx:
    port: 70
  ftp:
    userName: ftpuser
    passWord: 123
    host: 39.96.68.53
    port: 21
    root: /
    MaxTotal: 100
    MinIdel: 2
    MaxIdle: 5
    MaxWaitMillis: 3000

pagehelper:
  helper-dialect: mysql
  params: count
  reasonable: true
  support-methods-arguments: true

server:
  port: 9090
